name: Discussion Webhook

on:
  discussion:
    types: [created, edited]

jobs:
  notify_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Save discussion body to file
        run: |
          # payload를 body.txt 파일에 저장 (쉘이 직접 내용 해석 안함)
          printf '%s' "${{ github.event.discussion.body }}" > body.txt

      - name: Send Webhook on Discussion Creation or Edit
        run: |
          # 파일에서 읽어서 CR(\r) 제거 및 안전하게 JSON 문자열로 변환
          BODY=$(cat body.txt | tr -d '\r' | jq -Rs .)

          JSON=$(jq -nc --arg event "${{ github.event.action }}" \
                        --arg number "${{ github.event.discussion.number }}" \
                        --arg url "${{ github.event.discussion.html_url }}" \
                        --arg title "${{ github.event.discussion.title }}" \
                        --arg user "${{ github.event.discussion.user.login }}" \
                        --arg created_at "${{ github.event.discussion.created_at }}" \
                        --arg updated_at "${{ github.event.discussion.updated_at }}" \
                        --argjson body "$BODY" \
                        '{event: $event, discussion_number: $number, discussion_url: $url, title: $title, user: $user, created_at: $created_at, updated_at: $updated_at, body: $body}')

          curl -X POST "http://52.79.203.123:8080/api/github/webhook" \
               -H "Content-Type: application/json" \
               -d "$JSON"
