name: Discussion Webhook

on:
  discussion:
    types: [created, edited]

jobs:
  notify_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook on Discussion Creation or Edit
        run: |
          JSON='{
            "event": "${{ github.event.action }}",
            "discussion_number": "${{ github.event.discussion.number }}",
            "discussion_url": "${{ github.event.discussion.html_url }}",
            "title": "${{ github.event.discussion.title }}",
            "user": "${{ github.event.discussion.user.login }}",
            "created_at": "${{ github.event.discussion.created_at }}",
            "updated_at": "${{ github.event.discussion.updated_at }}",
            "body": "${{ github.event.discussion.body }}"
          }'

          # JSON에서 줄바꿈을 제거하고 한 줄로 변환
          JSON=$(echo "$JSON" | sed ':a;N;$!ba;s/\n/ /g')

          curl -X POST "http://52.79.203.123:8080/api/github/webhook" \
               -H "Content-Type: application/json" \
               -d "$JSON"
