name: Discussion Webhook

on:
  discussion:
    types: [created, edited]

jobs:
  notify_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook on Discussion Creation or Edit
        run: |
          BODY=$(printf '%s' "${{ github.event.discussion.body }}" | tr -d '\r' | jq -Rs .)

          JSON=$(jq -nc --arg event "${{ github.event.action }}" \
                        --arg number "${{ github.event.discussion.number }}" \
                        --arg url "${{ github.event.discussion.html_url }}" \
                        --arg title "${{ github.event.discussion.title }}" \
                        --arg user "${{ github.event.discussion.user.login }}" \
                        --arg created_at "${{ github.event.discussion.created_at }}" \
                        --arg updated_at "${{ github.event.discussion.updated_at }}" \
                        --arg body "$BODY" \
                        '{event: $event, discussion_number: $number, discussion_url: $url, title: $title, user: $user, created_at: $created_at, updated_at: $updated_at, body: $body}')

          curl -X POST "http://52.79.203.123:8080/api/github/webhook" \
               -H "Content-Type: application/json" \
               -d "$JSON"
